#!/usr/bin/env python3
# Exercise 2 — Python CDK parity
#
# Goal: Re-implement the EXACT stack from Exercise 1 (VPC + KMS-encrypted S3 with
#       lifecycle rules + a Lambda that reads from the bucket with least-privilege
#       IAM) in Python CDK, then confirm it synthesizes an EQUIVALENT CloudFormation
#       template to the TypeScript version.
#
# Estimated time: 75 minutes.
#
# HOW TO USE THIS FILE
#
# 1. Scaffold a fresh Python CDK app in a new folder:
#
#        mkdir crunch-iac-py && cd crunch-iac-py
#        cdk init app --language=python
#        source .venv/bin/activate
#        pip install -r requirements.txt
#
#    `cdk init` creates: app.py, cdk.json, a crunch_iac_py/ package with a
#    *_stack.py, and requirements.txt pinning aws-cdk-lib.
#
# 2. Copy the lambda/read_object.py handler from Exercise 1 into this project's
#    lambda/ folder (create it). It is identical — same handler, same runtime.
#
# 3. Replace the generated crunch_iac_py/crunch_iac_py_stack.py with the
#    `CrunchIacPyStack` class below, and replace app.py with the `app.py` block
#    at the bottom of this file.
#
# 4. Synthesize and compare against Exercise 1's template:
#
#        cdk synth > template-py.json
#        # In the Exercise 1 folder you already have cdk.out/CrunchIacTsStack.template.json
#        # Normalize both (logical-ID hashes differ) and diff the resource types/props.
#
# 5. For the FREE path, deploy to LocalStack with the cdklocal wrapper:
#
#        npm install -g aws-cdk-local       # if not already installed
#        cdklocal bootstrap
#        cdklocal deploy --require-approval never
#
# ACCEPTANCE CRITERIA
#
#   [ ] `cdk synth` succeeds with no unresolved tokens.
#   [ ] The Python template has the SAME set of AWS resource TYPES as the TS one
#       (same count of AWS::S3::Bucket, AWS::KMS::Key, AWS::Lambda::Function,
#        AWS::EC2::VPC, AWS::IAM::Role/Policy, AWS::S3::BucketPolicy, etc.).
#   [ ] The Lambda role policy contains s3:GetObject scoped to the bucket AND
#       kms:Decrypt scoped to the key — generated by grant_read, exactly as in TS.
#   [ ] You can explain WHY the logical IDs differ between the two templates but
#       the resources are equivalent (hint: the hash is derived from the construct
#       PATH, and the construct IDs/stack names differ between the two apps).
#
# WHY THIS EXERCISE EXISTS
#
#   CDK's L2 constructs are generated from a single source (jsii) and projected
#   into every supported language. So the TypeScript Bucket and the Python Bucket
#   are the SAME construct with the SAME defaults — they MUST synthesize to
#   equivalent CloudFormation. Proving it to yourself kills the myth that "Python
#   CDK is different from TS CDK." It is the same library, different syntax.

from aws_cdk import (
    Stack,
    Duration,
    RemovalPolicy,
    CfnOutput,
)
from aws_cdk import aws_kms as kms
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_lambda as lambda_
from constructs import Construct


class CrunchIacPyStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # --- VPC: two AZs, public + isolated subnets, NO NAT Gateway. ---
        vpc = ec2.Vpc(
            self,
            "Vpc",
            ip_addresses=ec2.IpAddresses.cidr("10.42.0.0/16"),
            max_azs=2,
            nat_gateways=0,  # deliberately zero — NAT is the silent budget killer
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="public", subnet_type=ec2.SubnetType.PUBLIC, cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
            ],
        )

        # --- KMS customer-managed key with rotation. ---
        key = kms.Key(
            self,
            "DataKey",
            enable_key_rotation=True,
            description="CMK for the Crunch IaC starter data bucket",
            removal_policy=RemovalPolicy.DESTROY,  # dev only; RETAIN in prod
        )

        # --- S3 bucket: KMS-encrypted, versioned, locked down, lifecycle rules. ---
        bucket = s3.Bucket(
            self,
            "Data",
            encryption=s3.BucketEncryption.KMS,
            encryption_key=key,
            bucket_key_enabled=True,  # reduce KMS API calls / cost
            enforce_ssl=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            versioned=True,
            removal_policy=RemovalPolicy.DESTROY,  # dev only; RETAIN in prod
            auto_delete_objects=True,  # dev only; lets `cdk destroy` empty the bucket
            lifecycle_rules=[
                s3.LifecycleRule(
                    id="tier-and-expire",
                    transitions=[
                        s3.Transition(
                            storage_class=s3.StorageClass.INFREQUENT_ACCESS,
                            transition_after=Duration.days(30),
                        )
                    ],
                    expiration=Duration.days(365),
                    noncurrent_version_expiration=Duration.days(90),
                )
            ],
        )

        # --- Lambda that reads from the bucket. ---
        reader = lambda_.Function(
            self,
            "Reader",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="read_object.handler",
            code=lambda_.Code.from_asset("lambda"),
            timeout=Duration.seconds(15),
            environment={"BUCKET_NAME": bucket.bucket_name},
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
            ),
        )

        # --- The one line that writes least-privilege IAM for you. ---
        # grant_read adds s3:GetObject/List* scoped to this bucket AND
        # kms:Decrypt on the key — identical to the TS grantRead.
        bucket.grant_read(reader)

        # --- Outputs. ---
        CfnOutput(self, "BucketName", value=bucket.bucket_name)
        CfnOutput(self, "KeyArn", value=key.key_arn)
        CfnOutput(self, "FunctionName", value=reader.function_name)


# ----------------------------------------------------------------------------
# app.py  (replace the generated app.py with this)
# ----------------------------------------------------------------------------
#
#   #!/usr/bin/env python3
#   import os
#   import aws_cdk as cdk
#   from crunch_iac_py.crunch_iac_py_stack import CrunchIacPyStack
#
#   app = cdk.App()
#   CrunchIacPyStack(
#       app,
#       "CrunchIacPyStack",
#       env=cdk.Environment(
#           account=os.getenv("CDK_DEFAULT_ACCOUNT"),
#           region=os.getenv("CDK_DEFAULT_REGION", "us-east-1"),
#       ),
#   )
#   app.synth()
#
# ----------------------------------------------------------------------------
# COMPARING THE TWO TEMPLATES
# ----------------------------------------------------------------------------
#
# The logical IDs differ (Data6E1F4D8F vs Data<other-hash>) because the hash is
# derived from the construct PATH, and the stack name differs (CrunchIacTsStack
# vs CrunchIacPyStack). But the RESOURCE TYPES and their PROPERTIES are equivalent.
#
# A quick structural comparison that ignores logical-ID names — count resource
# types in each template and confirm they match:
#
#   # requires jq
#   for f in ../crunch-iac-ts/cdk.out/CrunchIacTsStack.template.json \
#            cdk.out/CrunchIacPyStack.template.json; do
#     echo "== $f =="
#     jq -r '.Resources | to_entries[] | .value.Type' "$f" | sort | uniq -c | sort -rn
#   done
#
# Expected: both print the SAME counts per type, for example:
#
#       7 AWS::EC2::Subnet
#       4 AWS::EC2::RouteTable
#       ...
#       1 AWS::S3::Bucket
#       1 AWS::S3::BucketPolicy
#       1 AWS::KMS::Key
#       1 AWS::Lambda::Function
#       1 AWS::IAM::Role
#       1 AWS::IAM::Policy
#
# That identical type histogram is the proof of parity. The two languages are
# thin syntactic skins over the same jsii-generated construct library.
#
# ----------------------------------------------------------------------------
# HINTS (read only if stuck >15 min)
# ----------------------------------------------------------------------------
#
# - `cdk init app --language=python` puts your stack in
#   crunch_iac_py/crunch_iac_py_stack.py and names the class CrunchIacPyStack.
#   Match those names or update the import in app.py accordingly.
#
# - Property names in Python CDK are snake_case (enforce_ssl, block_public_access,
#   transition_after) where TS uses camelCase (enforceSSL, blockPublicAccess,
#   transitionAfter). The enum and class names are identical.
#
# - If `pip install -r requirements.txt` is slow or the version is old, pin the
#   latest v2: `pip install --upgrade "aws-cdk-lib>=2,<3" constructs`.
#
# - For the LocalStack deploy you do NOT need a real AWS account. cdklocal injects
#   a fake account 000000000000 and points the SDK at http://localhost:4566.
